### PR TITLE
HD-112342 Platform > Upgrade base libraries to latest version

### PR DESCRIPTION
**Pull request by dmaliwat**
## Ticket references
- [HD-112342](https://freedom.myjetbrains.com/youtrack/issue/HD-112342)

## Checklist

- [ ] bugfix
- [ ] new feature
- [ ] breaking change
- [ ] added unit tests
- [ ] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

## Testing

Just a bump version
image

### CODE REVIEW

**Review by dvikas — APPROVED** [review]

**Review by cedricabuso — DISMISSED** [review]

**Review by vcanonjr-freedom — APPROVED** [review]

**Comment by pandafox** [comment]
I assume we'd upgrade all the other repo as well?

**Comment by dmaliwat** [comment]
> I assume we'd upgrade all the other repo as well?

Will do it as well. thanks

**Review by jonelrempis — APPROVED** [review]

**Review by cedricabuso — APPROVED** [review]

**Comment by pandafox** [comment]
@dmaliwat 

Just a bump version is not really a meaningful testing, at least setup a do some sanity test?

**Comment by dmaliwat** [comment]
> @dmaliwat
> 
> Just a bump version is not really a meaningful testing, at least setup a do some sanity test?

@pandafox 
Sorry that screenshot is not a test, but I did test it on CID. And already told the team about it the day itself.
image


I also thought all PR's related to this are already released.

**Comment by vcanonjr-freedom** [comment]
* npm install

quasar-boiler-plate-axios-update-npm-install

* npm run dev

quasar-boiler-plate-axios-update-npm-run-dev

* Sample pages and tables

Screenshot 2021-06-09 at 14-38-41 Freedom App

Screenshot 2021-06-09 at 14-39-00 Freedom App

Screenshot 2021-06-09 at 14-39-34 Freedom App

**Pull request merged**
