### PR TITLE
Dev-3801 Dependency Issue > Lock all codebase vue and vue compiler version

### PR DESCRIPTION
**Pull request by jonelrempis**
## Ticket references
- [Dev-3801](https://freedom.myjetbrains.com/youtrack/issue/Dev-3801)

## Summary of changes
- Fix: matched  versions of vue and vue-template-compiler
- Feat: Updated depracated i18next-xhr-backend to i18next-http-backend

## Checklist

- [ ] bugfix
- [ ] new feature
- [ ] breaking change
- [ ] added unit tests
- [ ] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

## Testing

1. Run the following
```
rm -rf node_modules/
rm package-lock.json
npm i
npm run dev
```

2. Go to https://localhost:8080/table-with-tabs

### CODE REVIEW

**Review by wildtron — DISMISSED** [review]

**Review by dmaliwat — APPROVED** [review]
LGTM

**Review by amsanchez13 — APPROVED** [review]

**Review by dvikas — APPROVED** [review]

**Review by pandafox — APPROVED** [review]

**Review by cedricabuso — APPROVED** [review]

**Comment by vcanonjr-freedom** [comment]
BoilerPlateLockVueVersion1

BoilerPlateLockVueVersion2

Screenshot_2021-05-19 Freedom App

**Comment by amsanchez13** [comment]
image
image

**Pull request merged**
